Vagrant.configure("2") do |config|

  config.vm.define "node1" do |msqlserver|

    msqlserver.vm.box = "ubuntu/trusty64"

    msqlserver.vm.box_check_update = false

    msqlserver.vm.network "private_network", type: "static", ip: "192.168.156.10"

    msqlserver.vm.provider "virtualbox" do |vb|

      vb.gui = false
      vb.name = "node1"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define "preprodserver" do |webserver|

    webserver.vm.box = "bento/ubuntu-22.04"

    webserver.disksize.size = "50GB"

    webserver.vm.box_check_update = false

    webserver.vm.network "forwarded_port", guest: 8080, host: 8082

    webserver.vm.network "private_network", type: "static", ip: "192.168.156.11"

    webserver.vm.synced_folder "./tomcatwebapps", "/opt/tomcat/webapps"

    webserver.vm.provider "virtualbox" do |vb|

      vb.gui = false
      vb.name = "control-plane"
      vb.memory = "1024"
    end
  end

end
